### ISSUE TITLE
Variable Helical formula

### ISSUE THREAD

**Issue by condac** [moucha19/OpenSCAD-Fletching-jig#2]
I do not have a ton of archery experience so I am not sure exactly how people want a helical to look like but for me it does not look right. 
I was trying to do helical with a bit lower angles. And the angle where the fletching is contacting the shaft is not 90 deg all ower the length of the fletching. I thought the basic behind a helical was that the angle was 90 deg ower the entire lenght.

Looking at the code the twist is static `twist = -direction*15` this was maybe supposed to be dynamic?

Here is an image of the helical preset but the angle set to 1 deg. It is straight on the shaft side but on the fletching side it is at an extreme twist. 
![Screenshot at 2020-06-03 11-13-48](https://user-images.githubusercontent.com/1023885/83618898-6adb1000-a58b-11ea-9028-592e331ad7a5.png)

**Comment by moucha19** [comment]
Hello, I'm so sorry that I'm replying to this so late, but i haven't received any notification and I don't really check GitHub regularly because i hoped i would receive an email or something.

Anyways, you are absolutely correct, the twist is static and i chose a value that seemed reasonable to most of the helical jigs i printed. If I remember correctly, I was trying to fix this but it was really difficult to adjust this twist properly for different values. I could've probably hardcode different values for different ranges, and i will try to do so whenever i have time. 

However, if you have any idea how to calculate the twist value exactly, I'm open to suggestions!

**Comment by condac** [comment]
I also had the same problem with notifications, default settings do not notify you, so no problem. 

This was very long time ago so I do not remember what i did. But I have a branch where I have done something you can test. It adds a screw type to helical options.I have created a pull request for you to look and see if you want it.

**Comment by moucha19** [comment]
So I fixed the twist issue and it should now adjust to helical_adjust parameter automatically. However, i tried to make your linear implementation work, but it didn't play nicely with some parameters, especially direction and it seemed inconsistent. I tried to extrude straight line instead of bezier curve to emulate your idea, but for some reason, it never rendered correctly even though in preview it looked okay. I tried some fixes, but since regular helical should be working fine now, I removed it for now so that i can release working revision ASAP. 
Let me know if you're going to test it and if it's going to be okay! Thank you!
